export const PATH = {
    TESTS: "/tests",
    TEST_ID: "/test/:id",
    EDIT_TEST_ID: "/test/edit/:id",
    USERS: "/users",
    USER_ID: "/user/:id",
    EDIT_USER_ID: "/user/edit/:id",
    LOGIN: "/login",
    LOGOUT: "/logout",
    BRANCHES: "/branches",
    BRANCH_ID: "/branch/:id",
    EDIT_BRANCH_ID: "/branch/edit/:id",
    DEPARTMENTS: "/departments",
    DEPARTMENT_ID: "/department/:id",
    EDIT_DEPARTMENT_ID: "/department/edit/:id",
    DEVICES: "/devices",
    DEVICE_ID: "/device/:id",
    EDIT_DEVICE_ID: "/device/edit/:id",
    POSITIONS: "/positions",
    POSITION_ID: "/position/:id",
    EDIT_POSITION_ID: "/position/edit/:id",
    TICKETS: "/tickets",
    TICKET_ID: "/ticket/:id",
    EDIT_TICKET_ID: "/ticket/edit/:id",
}